### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by ralts00** [samknight/slack_applescript#9]
Thanks to your help, I can include the script, however I can't get it to run, it always marks me as a syntax error, could you let me know what I'm doing wrong?
the following example is from the documentation,
However, what I want to do is send a message to a specific channel.
:)
![Captura de pantalla 2020-07-08 15 19 50](https://user-images.githubusercontent.com/5034252/86966294-86a77800-c12e-11ea-95fa-3a62b0cabc21.png)

**Comment by samknight** [comment]
Hi

I'm really struggling to replicate this issue.

I'm going to suggest a couple of things and hopefully that will get us closer:

1. Please make sure you have downloaded the latest version of this library and have removed all other past versions of the library in other folders that may have been downloaded before.

2. Please move the library to the suggest place in the README and then add it to the library sidebar in Script Editor as shown on the screenshot. If it appears in bold instead of greyed out then it means it should be recognised properly

<img width="691" alt="Screenshot 2020-07-09 at 21 39 55" src="https://user-images.githubusercontent.com/204702/87088564-e84e0c00-c22c-11ea-85a8-9017e9a781a5.png">

3. Click on the dictionary icon in Script Editor to find the auto created docs - scroll down to "set do not disturb" - it should show the following

<img width="804" alt="Screenshot 2020-07-09 at 21 45 21" src="https://user-images.githubusercontent.com/204702/87088914-7fb35f00-c22d-11ea-8033-51c8a9a46259.png">

**Comment by ralts00** [comment]
Hello,
- Check that the most current file is in the folder mentioned in the README
- I couldn't add the Slack.scptd since that type of files is not supported by the libraries window.
- the library already appears in my dictionaries but it doesn't open anything if I want to open it.
- 2 computers that I have do the same.
What do you recommend me?
![Captura de pantalla 2020-07-09 16 21 41](https://user-images.githubusercontent.com/5034252/87099537-b5e1e600-c20f-11ea-9ef0-db2235e14206.png)

**Comment by samknight** [comment]
Hi I've added the script bundle inside a zipped folder and updated the readme advice. Please let me know if that works and then I will close the issue. Sorry it's taken so long to diagnose the problem

**Comment by ralts00** [comment]
Works!
thank you very very much.
It no longer throws the error, if I set the "do not disturb" status correctly for 30min
![Captura de pantalla 2020-07-18 12 41 18](https://user-images.githubusercontent.com/5034252/87858531-282f8600-c8f4-11ea-9721-89d48abcdd17.png)
